version: '3'

volumes:
  keycloak_data2:

services:

  usuarios-service:
    image: usuarios
    build: ./usuarios
    restart: always
    depends_on:
      - eureka-service
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.data.mongodb.uri: mongodb://localhost:27017/usuario



  eureka-service:
    image: eureka-server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    volumes:
      - keycloak_data2:/opt/keycloak/data/
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin


  login-service:
    image: login
    build: ./login
    restart: always
    depends_on:
      - keycloak
      - eureka-service
    environment:
      keycloak.admin-url: http://localhost:9090/realms/tutorial-api
      spring.security.oauth2.resource-server.jwt.issuer-uri: http://localhost:9090/realms/tutorial-api
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka

  gateway-service:
    image: gateway
    build: ./gateway
    restart: always
    depends_on:
      - eureka-service
      - usuarios-service
      - keycloak
      - login-service
    environment:

      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9090/realms/tutorial-api
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:9090/realms/tutorial-api/protocol/openid-connect/certs

    ports:
      - "8080:8080"