version: '2.17.3'

volumes:
  keycloak_data2:

services:

  gateway:
    image: gateway
    build: ./gateway
    restart: always
    depends_on:
      - eureka-server
      - keycloak
    environment:
      server.port: 8080
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/realms/tutorial-api
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/realms/tutorial-api/protocol/openid-connect/certs
    ports:
      - "8080:8082"

  eureka-server:
    image: eureka-server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    volumes:
      - keycloak_data2:/opt/keycloak/data/
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  login:
    image: login
    build: ./login
    restart: always
    depends_on:
      - keycloak
      - eureka-server
    environment:
      keycloack.admin-url: http://keycloak:8080/admin/realms/tutorial-api
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/realms/tutorial-api
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka